language: python
python:
  - "2.6"
  - "2.7"
env:
  - DJANGO_VERSION=1.3
  - DJANGO_VERSION=1.4
  - DJANGO_VERSION=1.5

install:
  - python setup.py install
  - pip install coveralls --use-mirrors
script:
  - python setup.py test

after_success:
  - coveralls